name: WineNotes
options:
  minimumXcodeGenVersion: 2.36.0
  deploymentTarget:
    iOS: 17.0
packages: {}
settings:
  base:
    SWIFT_VERSION: 5.10
    PRODUCT_BUNDLE_IDENTIFIER: com.example.WineNotes
    DEVELOPMENT_TEAM: YOUR_TEAM_ID
    INFOPLIST_FILE: Info.plist
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    CODE_SIGN_STYLE: Automatic
    TARGETED_DEVICE_FAMILY: 1

targets:
  WineNotes:
    type: application
    platform: iOS
    sources:
      - path: Sources
    settings:
      base:
        PRODUCT_NAME: "WineNotes"
    info:
      path: Info.plist
      properties:
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UILaunchScreen: {}
        UIRequiredDeviceCapabilities: [arm64]
    scheme:
      testTargets: []